---
sudo: false
language: ruby
cache: bundler
branches:
  only:
    - master
#- gemfiles/rails42.gemfile
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rspec
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
